### ISSUE TITLE
focus on search upon launch

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/Xaml-Controls-Gallery#109]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [ ] New sample
- [ ] Addition to existing sample
- [ ] Modification to existing sample
None of the above 

**If this is an addition/modification to an existing sample page, which one?**
None

**Describe the sample**

N/A

**Is your sample request related to a problem? Please describe it**

Not a sample request

**Additional context**

**Comment by chingucoding** [comment]
This seems like a good idea, since (at least for me) the most common use case is to look up a single component. Having the app focus the search box at start would make this a bit faster.

Currently the focus at start is on the "What's New" menu item, which is in a sense redundant since this is the page that is open at start.

If it is ok, I will be happy to change the focus to the search bar on startup :)

**Comment by YuliKl** [comment]
@chingucoding, please do make this change. Thank you!
