### ISSUE TITLE
Change the new/updated/preview tags for samples

### ISSUE THREAD

**Issue by YuliKl** [microsoft/Xaml-Controls-Gallery#140]
**Describe the bug**

The new/updated/preview designations haven't been updated in a little while. Feels like it's time to make a pass through the samples and update their status.

@stmoy, I would love your help in wrangling this information and filling out the **New state** column. (If the sample shouldn't appear on the What's New page, let's call its New state *None*.)

Sample name | Current state | New state
---|----|----
AnimatedVisualPlayer | New |
Animation interop | New |
ColorPaletteResources| New |
CommandBarFlyout | New | Updated
Compact Sizing | New |
Connected Animation | New |
DataGrid  | New |
DropDownButton | New |
Easing Functions | New |
Implicit Transitions | New |
ItemsReater | New | New
Page transitions | New |
SplitButton | New |
StandardUICommand | New | Updated
TeachingTip | New | New
Theme Transitions | New |
ToggleSplitButton | New |
WebView | New |
XamlUICommand | New |
ComboBox | Updated |
CommandBar| Updated |
ListView| Updated |
MenuBar| Updated | Updated
NavigationView| Updated | Updated
RichEditBox | Updated |
TreeView | Updated |
ScrollViewer (preview) | Preview | Preview
Acrylic | None | Updated
TabView | n/a | New

**Comment by stmoy** [comment]
Thanks for writing this up. I agree that we should update the new/updated/preview designations. A few thoughts:

> TeachingTip 

I'd argue that TeachingTip is still relatively "new" since it just came out last release. 

We've also got a few new controls/features coming down the pipe (TabView, corner radius) which will have New pages associated with them. I think we should aim to update the designations at the same time the next WinUI 2.X package comes out. Is that an ok timeframe?

**Comment by YuliKl** [comment]
Timeframe sounds good. I would like us to release a new Gallery version to the store by end of September, which I believe gives us a few weeks to update the app's WinUI package.

Will corner radius get its own page or just be incorporated into the appearance of the existing samples?

**Comment by stmoy** [comment]
Current POR is that @kikisaints will add a page for CornerRadius that links out to the theme tool, same as the ColorPaletteResources page. 

> Timeframe sounds good. I would like us to release a new Gallery version to the store by end of September, which I believe gives us a few weeks to update the app's WinUI package.

I'm thinking about releasing one sooner than that given all of the great work that @chingucoding has been doing. (Plus, the Acrylic page is crashing so that's another motivator >_> )

**Comment by YuliKl** [comment]
Sooner is also great. I'm hoping to be able to include a fix for #141, which is also gated on a new WinUI package. 

And huge thanks to @chingucoding for making so many improvements!
