### ISSUE TITLE
Update app logo 

### ISSUE THREAD

**Issue by stmoy** [microsoft/Xaml-Controls-Gallery#210]
The WinUI logo has recently been updated:
![logo](https://user-images.githubusercontent.com/16964652/64999910-57253780-d89e-11e9-9574-001800452a34.png)

Lets also update the Xaml Controls Gallery icon!
![image](https://user-images.githubusercontent.com/25991996/65558304-01c6d700-deeb-11e9-8388-f4676e0dc381.png)

Exactly how the logo should be updated is TBD - we're open to suggestions!

**Comment by chingucoding** [comment]
We could replace the old XAML logo in the middle with the new WinUI logo:
![XCG_WithNewWinUI_Logo](https://user-images.githubusercontent.com/16122379/65815806-5f616900-e1f4-11e9-95fc-597e7629f336.png)

However, the new WinUI logo is quite detailed, so not that sharp and crisp in low resolutions.
Using the low resolution version provided by @mdtauk, we could do this:

![XCG_WithNewWinUI_Logo_Improved](https://user-images.githubusercontent.com/16122379/65815905-5d4bda00-e1f5-11e9-8ce6-bdf7e399dfb3.png)

**Comment by mdtauk** [comment]
I am happy to leave it to the community to decide this new logo :D

But rather than putting one logo onto the other, why not rethink it...

![image](https://user-images.githubusercontent.com/7389110/65818833-5f219780-e20d-11e9-8fcb-4d6f70c6412b.png)

Especially when you move down to the 16px icon sizes, it will be harder to integrate the WinUI logo into any other shapes.

**Comment by stmoy** [comment]
Lets continue the conversation on #374
