### ISSUE TITLE
Link to the Ink Toolbar control leads to a blank page.

### ISSUE THREAD

**Issue by yaichenbaum** [microsoft/Xaml-Controls-Gallery#296]
**Expected behavior**
I would expect the Ink Toolbar link to go to the Ink Toolbar page.

**Actual behavior**
It shows a blank page instead of the actual Ink Toolbar smaples.

**Version**
Gallery version 1.2.11

**Location**
Found on InkCanvas page where it shows related controls.

**Screenshots**
![image](https://user-images.githubusercontent.com/39923744/70648750-bc789280-1c19-11ea-96e3-b92c0cf369a1.png)

![image](https://user-images.githubusercontent.com/39923744/70648645-89ce9a00-1c19-11ea-9202-83f0137a2e5d.png)

**Comment by stmoy** [comment]
Thank you for reporting this issue. As it turns out, there isn't an ink toolbar page 😅

The fix for this issue consists of two steps:
1) Remove the broken link for now
2) Add an ink toolbar sample (and re-add the link) #297 

What sorts of content would you like to see on the InkToolbar page? Please add comments to #297 about what features you'd like to see sampled.
