### ISSUE TITLE
What's New header blocks scrollbar

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/Xaml-Controls-Gallery#338]
**Describe the bug**

What's New header blocks scrollbar

**Steps to reproduce the bug**

1. Open XAML Controls Gallery

**Expected behavior**

Scrollbar goes from bottom of window to header

**Actual behavior**

Scrollbar spans whole height

**Screenshots**

![image](https://user-images.githubusercontent.com/51363864/73128950-67a7a480-402c-11ea-9955-d12e59c4f249.png)

**Version Info**

Gallery version (found on Settings page): 

1.2.12.0
Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] 1909 (whatever build that is)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

I have disabled automatically hiding scrollbars. it's also worth noting that the scrollbar obscures the navigationview. i've probably made another bug report

**Comment by stmoy** [comment]
@YuliKl - I thought you fixed this? Any ideas?

**Comment by YuliKl** [comment]
@Poopooracoocoo I'm not sure I understand the problem, can you provide a little more detail about what's wrong with the current behavior? And more detailed repro steps? 

Your screenshot shows two scrollbars. Do you have the "Automatically hide scroll bars in Windows" setting toggled Off? Which of the two scrollbars do you feel is problematic?

**Comment by Poopooracoocoo** [comment]
@YuliKl 

i was referring to the srcollbar on the right. you can't access the top tack

and yeah i have automatically hide scrollbars off as i said

**Comment by YuliKl** [comment]
@Poopooracoocoo I see. You're referring to this: ![image](https://user-images.githubusercontent.com/13142665/73429388-6c9c7a80-42f0-11ea-85c2-0198b169e21a.png)

I don't know how to fix this while the Gallery draws content into the title bar. In my repro, it's the Close buttons that's causing problems by always being on top. I don't believe that shortening the ScrollViewer is an option either because of the way the sticky headers are implemented.

If someone has a creative solution I'm all ears, but I suspect we'll need to live with this particular bug.

**Comment by Poopooracoocoo** [comment]
@yulikl do you think an issue on winui should be made?

**Comment by YuliKl** [comment]
> @YuliKl do you think an issue on winui should be made?

No. This is an app issue, I don't think the framework can fix it.

**Comment by gregwoo-microsoft** [comment]
Closing this as it is no longer present in the current XCG version.
