### ISSUE TITLE
[Feature request] Modernizing the XAML Controls Gallery icon

### ISSUE THREAD

**Issue by niels9001** [microsoft/Xaml-Controls-Gallery#374]
# Summary of the new feature/enhancement

The current XAML Controls Gallery icon is in the MDL2 style. Since WinUI is modernizing the Windows XAML platform, the gallery app icon should reflect this as well. It should be at the front of innovation and reflect the latest changes of the Windows platform. In 2020, we'll see lots of inbox application icons modernized ([more on Microsoft Design's push to re-design hundreds of OS icons here](https://medium.com/microsoft-design/the-ripple-effect-expanding-our-icon-design-system-74b4d916b7a4)).

# Proposed technical implementation details

The proposal is to redesign the current XAML Controls Gallery icon, so it feels part of the Windows 10 family of experiences (e.g. Terminal, other inbox apps)

- While add it, maybe we need to change the (tile) accent color as well so it fits in a bit more with the other icons.

- Would be nice if we can bring the WinUI logo to this app icon as well!
![logo](https://user-images.githubusercontent.com/16964652/64999910-57253780-d89e-11e9-9574-001800452a34.png)

For context, here is the current Xaml Controls Gallery icon: 
![image](https://user-images.githubusercontent.com/25991996/65558304-01c6d700-deeb-11e9-8388-f4676e0dc381.png)

Windows Community Toolkit Sample App app icon issue: https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3182

**Comment by niels9001** [comment]
I gave it a shot.. This is a 1:1 port to the newer style. Concept 2 is using similar colors like the new Calculator icon.

![Artboard 1 – 13](https://user-images.githubusercontent.com/9866362/76442208-df554700-63c0-11ea-803c-26f7daa7d5f0.png)

**Comment by mdtauk** [comment]
![Final Blue Logo Shapes _ Shaded 1024](https://user-images.githubusercontent.com/7389110/76443001-aa91c180-63b9-11ea-99c1-2ef5362479ce.png)

I designed the WinUI Library logo, and so something linked to it may make sense.  There was talk at the time about the app possibly being renamed WinUI Controls Gallery.

![CURRENT](https://user-images.githubusercontent.com/7389110/76443202-f9d7f200-63b9-11ea-8230-a5371f61ae46.png)

Some of the early ideas I proposed for the WinUI logo was designing the 3 matching logos

![image](https://user-images.githubusercontent.com/7389110/76443346-2e4bae00-63ba-11ea-92e5-93377e9d9265.png)

**Comment by chingucoding** [comment]
I think it would be better to continue this discussion in #210 , so that we don't have multiple threads for the same issue.

**Comment by stmoy** [comment]
Agreed that we shouldn't have multiple threads on this issue. I think we're going to get more traction on this thread, so I'm going to close #210 as a dupe and localize the conversation here.

**Comment by stmoy** [comment]
@niels9001 - I'm loving this direction as it seems like a natural evolution of the existing icon. A thought: what if it incorporated more color? I'm thinking something like the blue in the Mail icon: 
![image](https://user-images.githubusercontent.com/25991996/76449568-8a4a0e80-6389-11ea-94c1-3b234ac2321b.png)

**Comment by salmanmkc** [comment]
Wasn't this an old issue before?

**Comment by salmanmkc** [comment]
Excited about this, I can have a go at doing some designs, but not sure I'll be able to come up with something fruitful 😅

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/76459918-73b8ad00-63b3-11ea-9224-077d9a4d0514.png)

Here are three concepts I came up with.

**Comment by mdtauk** [comment]
![image](https://user-images.githubusercontent.com/7389110/76462147-1899b100-63d9-11ea-9184-cccd674bfc85.png)

Just a quick idea

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/76463179-5b4b9100-63b9-11ea-88c0-98806fbc4321.png)
Here are two more concepts I came up with.

**Comment by yaichenbaum** [comment]
Just a recommendation, if someone downvotes an idea, they should explain why. Without context, it makes it harder for everyone to work on and improve their designs.

**Comment by SavoySchuler** [comment]
@mdtauk, I _really_ like the concept behind what you posted on the other thread (linked below) because it establishes this idea that the Xaml Controls Gallery (XCG) is a **breakdown** or **dissection** of WinUI's control offering. It gives me this "let's look at the inside of it" feeling that's an inherent step in a developer's journey. 

https://github.com/microsoft/Xaml-Controls-Gallery/issues/210#issuecomment-536199523

![image](https://user-images.githubusercontent.com/16964652/76466179-5defbb80-63a4-11ea-9ed1-94c4236abfd3.png)


Please don't let me over influence this conversation though. @stmoy is the app owner, I'm just joining in on the fun. 😄

**Comment by mdtauk** [comment]
Another idea

![image](https://user-images.githubusercontent.com/7389110/76469126-864bda00-63e5-11ea-965e-818b384fb460.png)

**Comment by niels9001** [comment]
@mdtauk Great stuff! I really like your concept where we have a similar style for all 3 icons (well at least XAML Controls and the Toolkit, since these are actual apps).

It's important that these icon scale well as well - would be nice to see some smaller versions (and maybe on a tile?) to see how that would work.

Ideally we'd create some sort of template we can all use and test these!

**Comment by yaichenbaum** [comment]
I created a basic template based on @niels9001 idea, I will continue working on it and adding additional places to visualize the icon at different scales.

https://www.figma.com/file/XpDRbAlSKC9rV3MNLqAPJS/XAML-Controls-Gallery-Icon?node-id=0%3A1

**Comment by mdtauk** [comment]
> @mdtauk Great stuff! I really like your concept where we have a similar style for all 3 icons (well at least XAML Controls and the Toolkit, since these are actual apps).
> 
> It's important that these icon scale well as well - would be nice to see some smaller versions (and maybe on a tile?) to see how that would work.
> 
> Ideally we'd create some sort of template we can all use and test these!

![image](https://user-images.githubusercontent.com/7389110/76472051-53591480-63ec-11ea-864e-694ae742e15d.png)

**Comment by zeealeid** [comment]
Here's my attempt — it is heavily inspired by the great work done by @niels9001 and @mdtauk ! :)
<img width="1800" alt="i suck at designing" src="https://user-images.githubusercontent.com/54409865/76517306-e3479e80-647e-11ea-8d0f-68b33bcbcc1f.png">

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/76526870-97780380-6444-11ea-97bb-118bfd3e0d75.png)
Here is another concept.

**Comment by stmoy** [comment]
I love the creativity and inspiration shown on this thread! 

I'm noticing some themes that I wanted to highlight for more riffing:
1. Many of the icons are a stack or collection of elements. I really like this motif because the Gallery is fundamentally a collection of samples and controls. 
![image](https://user-images.githubusercontent.com/25991996/76546057-11f65280-6448-11ea-9d47-e5ff7ab46334.png)
![image](https://user-images.githubusercontent.com/25991996/76546098-25a1b900-6448-11ea-964e-dcec2937e302.png)


2. Many submissions include `< / >` - this metaphor directly relates to the markup part of Xaml. Even the new WinUI logo incorporates the brackets - but in a more subtle, nuanced way. I wonder if we need to overtly include `< / >` or if the icon can be more subtle about the brackets? More specifically, I wonder if it'd be possible to directly incorporate the WinUI logo in the icon to make the relationship more explicit? 
![image](https://user-images.githubusercontent.com/25991996/76545992-f25f2a00-6447-11ea-996d-f11b04c5918b.png)
![image](https://user-images.githubusercontent.com/25991996/76546011-fc812880-6447-11ea-995d-d1c81cab4afe.png)

3. The new Fluent iconography includes depth, color, texture, and shadows. In contrast, the old XCG icon was flat-white per MDL2 guidelines. Most of the submissions in this thread include depth, shadows, and texture - but I'd love to see how color can also be used in creative ways to do things like build hierarchy. 
![image](https://user-images.githubusercontent.com/25991996/76545925-d65b8880-6447-11ea-9fe9-49a8ca1c74af.png)
![image](https://user-images.githubusercontent.com/25991996/76545967-e83d2b80-6447-11ea-8ddf-52b625235c54.png)



I'm so excited to see what you come up with. Y'all rock.

**Comment by yaichenbaum** [comment]
Here are a few more ideas.
![image](https://user-images.githubusercontent.com/39923744/76548711-8db2c800-6465-11ea-80b6-528947326a08.png)

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/76550502-9e187200-6468-11ea-9668-af311c500d0c.png)

**Comment by mdtauk** [comment]
![image](https://user-images.githubusercontent.com/7389110/76556210-011dff00-6491-11ea-9c5d-0c05daaa63df.png)

**Comment by Felix-Dev** [comment]
I like the concepts
![image](https://user-images.githubusercontent.com/1398851/76631479-0dae6000-6542-11ea-8566-43e6d338f3c3.png)
and 
![image](https://user-images.githubusercontent.com/1398851/76631560-2fa7e280-6542-11ea-848a-bd75f91fb5fd.png)
the most for now have they are referencing the WinUI product while also reflecting the building-blocks showcase nature of the Xaml Controls Gallery app.

I don't think we need to make the new logo cupe based as theat adds additional load to the user's eyes as seen in the cases so far (3D + different depth + different colors) and to be honest, I'm having a bit of a challenge to read the XCG's mission out of these versions for now.

As such, my current preferences are the two concepts shown above as they perfectly cover the connection to WinUI and the control-sample nature of the XCG!

**Comment by salmanmkc** [comment]
I'm not that good at designs, but here's potentially something for inspiration:
![xamlcontrolgallerydesign](https://user-images.githubusercontent.com/32169182/77249985-be9cb500-6c3c-11ea-9960-78f0e934fdac.png)
I like the idea of having a file tab since it indicates that it can be searched through. This is just one draft but I'm happy to go back and make changes/share the file based on feedback.

**Comment by stmoy** [comment]
I couldn't let you have all the fun without me! 😉

The general consensus across Twitter and GitHub is that folks loved @niels9001's original concepts:
![image](https://user-images.githubusercontent.com/9866362/76442208-df554700-63c0-11ea-803c-26f7daa7d5f0.png)

I really liked that these concepts added some Fluent flair to the original Gallery icon while still maintaining consistency with the current layered icon. However, I'd really like to take this opportunity to move to something a bit more colorful. 

Taking inspiration from the above concepts, I created this:
![image](https://user-images.githubusercontent.com/25991996/77385362-22120a00-6d45-11ea-8b70-1ae00ef80fbe.png)

![image](https://user-images.githubusercontent.com/25991996/77385384-30602600-6d45-11ea-9718-cf08cf828147.png)

This icon moves away from the current Gallery color and instead aligns with the colors found in the WinUI logo.

Thoughts? Because Niels's logo had the most positive feedback and because I really want some color in the logo, we're probably going to go with this version pending significant feedback.

**Comment by yaichenbaum** [comment]
@stmoy I would soften the corner radii to match the new fabric icons released in Windows 10.

**Comment by niels9001** [comment]
@stmoy

I love that!!! Adding the WinUI color looks great! Maybe change the corner radius (as @yaichenbaum mentioned) so it's slightly less round and in line with the other icons?

I think you have a winner here! Would be nice to have a similar version of that for the Community Toolkit app as other proposed above :)? I will open up an issue on their repo as well and mention this one!

**Comment by Felix-Dev** [comment]
Second what @yaichenbaum and @niels9001 suggested about softening the corner radius 🙂

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/77456839-36501880-6dd2-11ea-9ecf-744f3508f9eb.png)

**Comment by stmoy** [comment]
Agree with the tighter corners. How does this look? I used @yaichenbaum's previous reply as a guide. I also slightly modified the shadows. 

![image](https://user-images.githubusercontent.com/25991996/77492337-9314f880-6dfd-11ea-9747-11c476c20e14.png)


![image](https://user-images.githubusercontent.com/25991996/77491998-95c31e00-6dfc-11ea-9b87-92159d000fbe.png)

This gif compares the old and new:
![oldvsnew](https://user-images.githubusercontent.com/25991996/77492180-1b46ce00-6dfd-11ea-9d7b-16ff453da60b.gif)

**Comment by yaichenbaum** [comment]
It looks really good! Would it be possible to get someone who worked on the other new icons in Windows 10 to look it over and see if it can be polished a bit further?
