### ISSUE TITLE
Behavior of Animation Scrolling and Content display buttons in ItemsRepeater sample page is confusing

### ISSUE THREAD

**Issue by YuliKl** [microsoft/Xaml-Controls-Gallery#376]
**Describe the bug**

When using touch narrator to scroll items in this sample, it may be difficult for users to understand the behavior they're seeing. The color swatch changes based on which item is centered in the ItemsRepeater, but it may not be obvious what's causing the color to change.

**Steps to reproduce the bug**

1. Launch XAML Controls Gallery and turn on narrator.
2. Activate Items Repeater from All Controls Page.
3. Navigate to first button present under "Animated Scrolling and Content Display" and swipe right and check if color changes or not,swipe right 4-5 times and simultaneously observe if color is changing or not.

**Expected behavior**

Color should not change on item navigation and it should change only when its activated with double tap.

**Actual behavior**

For 1st few buttons the color doesn't change but when we move forward the color changes but its not in sync .

**Screenshots**

![image](https://user-images.githubusercontent.com/13142665/76571024-cf4a6f80-6473-11ea-9089-7d478ee7f748.png)

**Version Info**

Gallery version (found on Settings page): 

1.2.13.0

**Additional context**

Copied from [internal bug](https://microsoft.visualstudio.com/OS/_workitems/edit/25469691)

**Comment by YuliKl** [comment]
@anawishnoff FYI. Looking for ideas to make this sample more accessible.

**Comment by anawishnoff** [comment]
@YuliKl 

Not sure if I totally understand the bug. As for the intended behavior: the color in the square is supposed to change as the list is scrolled. When one button becomes closest to the middle (and therefore it has the largest size), the color in the square should match the color of the button. The color in the square should also change if you click once on a button - the square should match the color of the clicked button.

So it's true that the first few colors will never get shown in the big square simply by scrolling, because their size won't change as they can't move closer to the middle. With regards to this, would it make sense to have the list be infinitely scroll-able (no set top or bottom)? That would make it so any color is able to reach the middle.

For accessibility options: I'm not too familiar with working with the narrator, but if it's possible to program to a narrator directly, I think it would be helpful to describe the size of the button as the user scrolls ("Aqua button is getting smaller" or "Aqua button is now in the middle"). Once again, not sure how feasible that is - let me know if something like that would help.

**Comment by chingucoding** [comment]
I am not sure if there would be a way to make this sample really accessible for touch screen users. After all, the changes we have are just visual changes. We could try to announce that the color changed, however I am not sure how helpful the sample be for users with narrator would be in that case (it would seem just like a list with colors, which based on scroll selects an item).
