### ISSUE TITLE
PageFooter issue for NavigationView

### ISSUE THREAD

**Issue by JonPerkinsOldGit** [microsoft/Xaml-Controls-Gallery#432]
**Description**
Adding a muxc:NavigationViewItem object as the NavigationView.PageFooter causes a crash.

Steps to reproduce the bug:
>> NB I am literally one week into using using WinUI and am also a newbie with UWP so apologies if I am missing something here. 
I originally started building my first app with the standard toolbox controls for a UWP app. However, I also got reading the WinUI documentation and added the necessary changes to my app to incorporate the muxc namespace. From here on I got a consistent unhandled exception error at application start that I tracked down to setting the PageFooter value with a muxc:NavigateViewItem instance. I discovered that this problem disappeared if I fell back to the standard version (i.e. removed the muxc: prefix from the NavigateViewItem).
I then installed the reference XAML Controls Gallery app onto a different computer, went to the NavigationView page, and then scrolled down to near the bottom of the page where there are some interactive controls to demonstrate behaviour. The moment I checked the "PaneFooter Visible" checkbox the app crashed too.

**Expected behavior**
Non crash

**Actual behavior**
Crash

**Screenshots**
(Fairly easy to reproduce, in my experience)

**Version Info**
Microsoft.UI.Xaml version 2.4.0 (latest stable from May 05, 2020)

Gallery version (found on Settings page): 
1.2.15

Windows 10 version:
- [ X] November 2019 Update (18363)

Device form factor:
- [ X] Desktop

**Comment by chingucoding** [comment]
Hi @JonperkinsOldGit !

Great to hear that you are trying out WinUI! The issue you are describing has been present in the "normal" WinUI 2.4.0 release, you are not doing anything wrong there. Luckily the latest WinUI 2.4 prerelease for that. If you use that prerelease, your app shouldn't crash anymore.

Also, the WinUI source code is open source and available here: https://github.com/microsoft/microsoft-ui-xaml
If you have questions or find a bug related to WinUI, you can file an issue over at that repo, since this repository only contains the source code of the XAML Controls Gallery app.

**Comment by JonPerkinsOldGit** [comment]
Excellent - will do. Thanks for the fast response Marcus :-)
