### ISSUE TITLE
suggestion: show interaction possibilities between controls

### ISSUE THREAD

**Issue by Jay-o-Way** [microsoft/Xaml-Controls-Gallery#618]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [ ] New sample
- [ ] Addition to existing sample
- [x] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**

The page that shows the TOGGLE SWITCH.

**Describe the sample**

This page shows two simple toggle switches. The second one determines the state of a connected ProgressRing. On the right side, there are a few links to some other "related controls". The ProgressRing is not amongst them. Since the direct relation (the IsActive property with a bind to the toggle) is _not_ shown on the page (or the code) in the Controls Gallery app, it would be nice to have a link to the page for the ProgressRing, hoping to find a code example that shows how to use the `IsActive="{x:Bind ToggleSwitch2.IsOn, Mode=OneWay}"` function.

**Is your sample request related to a problem? Please describe it**

Nope.

**Additional context**

For people that are still new to this coding, it would be interesting to see how two different controls can interact with each other. In this case, the `IsActive` property can be an example for methods.

**Comment by chingucoding** [comment]
I'm not entirely sure if I understand this correctly. Would it help you if the toggle switch sample code to include the binding between the ToggleSwitch and the ProgressRing?

@stmoy Should we update the sample to use the new WinUI ProgressRing?

**Comment by Jay-o-Way** [comment]
> I'm not entirely sure if I understand this correctly.

I was afraid of that. Here's a quick drawing.
![image](https://user-images.githubusercontent.com/65828559/103181302-06bdc780-48a0-11eb-80e3-bbe11d56a1a6.png)
Since the ProgressRing is _used_ in an example, I'm thinking it might be handy to have a direct link to that control, right next to it.

> Would it help you if the toggle switch sample code to include the binding between the ToggleSwitch and the ProgressRing?

Yes, that too. I'm still pretty new to this and I think this would show the relation between these two controls. You can find it in the [online source code](https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/ControlPages/ToggleSwitchPage.xaml), but including it in the example code in the app would be handy.

**Comment by chingucoding** [comment]
Ah I see. The "Related Controls" section is about controls that are either similar or are closely related such as TabView and TabViewItem. The only "connection" between ProgressRing and ToggleSwitch is that they happen to be in one sample, in apps however those two controls don't have many similarities or occur together often. But I don't have a strong opinion on this, let @stmoy weigh in on this.

> Yes, that too. I'm still pretty new to this and I think this would show the relation between these two controls. You can find it in the online source code, but including it in the example code in the app would be handy.

Right. If you want to, you can create a PR for this to update the code sample, otherwise, I would create a PR to update the sample code.

**Comment by Jay-o-Way** [comment]
@chingucoding I see your point on the "Related controls". I think there's something to say for both points of view. _"to include, or not to include"_.

Uhm, I wouldn't know how to create a PR for this. But if you agree on the idea, feel free.

**Comment by chingucoding** [comment]
> Uhm, I wouldn't know how to create a PR for this. But if you agree on the idea, feel free.

You would only need to update the following line https://github.com/microsoft/Xaml-Controls-Gallery/blob/66cccbb5075ff615ce2870b289f616f08851909a/XamlControlsGallery/ControlPages/ToggleSwitchPage.xaml#L38
to include the progressring, essentially just copying https://github.com/microsoft/Xaml-Controls-Gallery/blob/66cccbb5075ff615ce2870b289f616f08851909a/XamlControlsGallery/ControlPages/ToggleSwitchPage.xaml#L33-L34 with small adjustments in there. So if you would like, you can create the PR and if there are questions, I would be more than happy to answer them, but of course it's fine if you don't want to :)

**Comment by Jay-o-Way** [comment]
I see it, but I can't change it on github.com. I can edit the page/file on my computer with Visual Studio, but I don't know how to upload/push that to create a PR. Can you do this? 

```
Cloning into 'D:\Visual Studio\solutions\XAML'...
POST git-upload-pack (174 bytes)
POST git-upload-pack (gzip 12912 to 5442 bytes)
Remote: Enumerating objects: 4566, done.        
Remote: Total 4566 (delta 0), reused 0 (delta 0), pack-reused 4566        
Opening repositories:
D:\Visual Studio\solutions\XAML
Pushing master
Remote: Permission to microsoft/Xaml-Controls-Gallery.git denied to Jay-o-Way.
Error encountered while pushing to the remote repository: Git failed with a fatal error.
unable to access 'https://github.com/microsoft/Xaml-Controls-Gallery/': The requested URL returned error: 403
Pushing to https://github.com/microsoft/Xaml-Controls-Gallery

Failed to push to the remote repository. See the Output window for more details.
Commit 3c98a214 created locally in repository D:\Visual Studio\solutions\XAML
Pushing master
Remote: Permission to microsoft/Xaml-Controls-Gallery.git denied to Jay-o-Way.
Error encountered while pushing to the remote repository: Git failed with a fatal error.
unable to access 'https://github.com/microsoft/Xaml-Controls-Gallery/': The requested URL returned error: 403
Pushing to https://github.com/microsoft/Xaml-Controls-Gallery

Failed to push to the remote repository. See the Output window for more details.
```

**Comment by chingucoding** [comment]
To create a PR, you will first need to create a fork of this repository. Then you will need to push the changes to your fork, after that you can create a PR with the changes. This article explains the steps a bit more clearly: https://gist.github.com/Chaser324/ce0505fbed06b947d962

You can create a fork of this repository by opening this repositories site and clicking "Fork" in the top left:
![image](https://user-images.githubusercontent.com/16122379/103183249-6a9cbc00-48b1-11eb-88b7-2215d3984404.png)

After that, you should be able to follow the steps in the linked gist. Since you already have your changes in a repository, I would recommend cloning your fork into a different folder and then manually copy the changed files over.

> @chingucoding I would include the StackPanel too.
Yes agreed, the StackPanel seems like a good idea to include too!

**Comment by Jay-o-Way** [comment]
I did it 😁

**Comment by chingucoding** [comment]
> I did it 😁

Yay 🎉. I'll review the PR shortly :)

**Comment by Jay-o-Way** [comment]
@stmoy do you have an opinion on having a link to controls, that are used in the examples? Even if they are a bit less related to the specific control of that specific page?

**Comment by stmoy** [comment]
Thanks for the ping @Jay-o-Way - I'm still trying to dig myself out of the holiday backlog 😅

In general, @chingucoding is correct in this assessment: 

> The "Related Controls" section is about controls that are either similar or are closely related such as TabView and TabViewItem. The only "connection" between ProgressRing and ToggleSwitch is that they happen to be in one sample, in apps however those two controls don't have many similarities or **occur together often.**

(Emphasis mine). Although this specific sample pairs these two controls, I don't actually expect this to be a super common case. Additionally, since the ProgressRing isn't initially visible on the page, they might be confused to see ProgressRing in the "related controls" section unless they know it is used in the sample. 

Some of our more complex samples (like those on the Connected Animations page) are actually composites of a bunch of different controls - things like ListView, StackPanel, TextBlocks, Images, etc. - so rather than exploding the Related Controls section with these supplemental links, we focus that area on the links to highly related controls that might not be as apparent on the page.

All of that is to say that I don't think we should add these controls into the Related controls section. If we wanted to go this direction, I think a new section would be more appropriate (something like "Controls used in this sample") - but even then, I'm afraid that list would get super long.

**Comment by chingucoding** [comment]
@stmoy Would you say this is a "won't fix" then at the current moment? Another idea we could do is have the "related controls" section be collapse and be collapsed by default. That would also be a good way to utilize the new WinUI Expander control in the XCG!

**Comment by stmoy** [comment]
Yup, this is currently a "won't fix" - closing. Even so, @Jay-o-Way, if you have other thoughts, please do feel free to add them to this  thread as we'll still get updates even if it is closed.

**Comment by Jay-o-Way** [comment]
It's okay, I understand. It was an idea, but you have a good answer.
