### ISSUE TITLE
Counter clockwise progress on the Progress Ring

### ISSUE THREAD

**Issue by irakandjii** [microsoft/Xaml-Controls-Gallery#629]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [ ] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**
ProgressRing

**Describe the sample**

indeterminate progress ring
spins counter clockwise -> signifies undoing

determinate progress ring modification
Allow progress ring to display counter clockwise (negative values) .  Imagine a steering wheel displaying the amount of clockwise or counterclockwise rotation.

-> signifies deviation from a center point or norm

**Comment by stmoy** [comment]
Hi @irakandjii - this would be a change to the base Progress Ring control rather than a change in the Gallery. This feedback would be more effective on the WinUI repo where these sorts of control changes are made. Please consider opening a new issue there: https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose
