### ISSUE TITLE
Draw UI to the Edge of the screen

### ISSUE THREAD

**Issue by Brouilles** [microsoft/Xaml-Controls-Gallery#655]
**Describe the bug**
On Xbox, the app don't fit the screen. Instead we have borders.

**Steps to reproduce the bug**
1. Download XAML Controls Gallery on Xbox OS (One / Series S/X)
2. Open the app.

**Expected behavior**
Fit the screen.

**Actual behavior**
Have bad borders.

**Screenshots**
![PXL_20210318_215134515.jpg](https://user-images.githubusercontent.com/1573282/111702426-896d7780-883c-11eb-87c3-9846c831be46.jpg)

(Sorry, because it's not a game. Xbox don't allow me to capture the screen).

I think it's related to https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/turn-off-overscan

Device form factor:
- [ ] Desktop
- [ ] Mobile
- [x] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by YuliKl** [comment]
@Brouilles this behavior is expected. TVs can overdraw and it's important for apps to provide a buffer so that important content doesn't get clipped on some users' hardware. More information here: https://docs.microsoft.com/en-us/windows/uwp/design/devices/designing-for-tv#tv-safe-area

**Comment by Brouilles** [comment]
It's weird. Not consistant. No way to enhance this? 
I know the Chromuim Edge is now "Fullscreen" whereas the Edge lagacy on Xbox is not.

**Comment by YuliKl** [comment]
This behavior has nothing to do with Edge. It's because Xboxes are typically hooked up to televisions not monitors. Monitors have precise pixel rendering and can be adjusted to make sure content never draws outside the monitor's visible area. TVs make no such promises so we strongly recommend building in a safe area, which will be visible on some TVs and not visible on other TVs.
