### ISSUE TITLE
InfoBadge with Dynamic Value Negative Value >> App Crash

### ISSUE THREAD

**Issue by MrSheeshs** [microsoft/Xaml-Controls-Gallery#826]
App Crash when InfoBadge Value is negative.

Menu "Status and Info" >> "InfoBage" >> Last Tutorial.

![image](https://user-images.githubusercontent.com/62643836/144594660-d4f696dc-ae9a-440b-a25c-086c2f96ee2c.png)
![image](https://user-images.githubusercontent.com/62643836/144594785-9065cffb-2197-4079-9068-e33792acc99c.png)

![image](https://user-images.githubusercontent.com/62643836/144594863-c62d4f7a-c9df-4d7a-8607-f6c485746c18.png)

**Comment by chingucoding** [comment]
What steps did you follow to get the app to crash? When I opened the last sample and entered a negative number, the app did not crash on my machine.

**Comment by gregwoo-microsoft** [comment]
Did not crash on mine either. Let us know if we can help :)

**Comment by MrSheeshs** [comment]
steps: "Status and Info" >> "InfoBage" >> "InfoBadge with Dynamic Value".
When i go below "-1", the app will crash 
![image](https://user-images.githubusercontent.com/62643836/146202255-de5ee109-8b23-41f3-817c-9e1b767b3d02.png)

**Comment by gregwoo-microsoft** [comment]
If you pull the latest version of the master branch, you will see that this problem was fixed (see picture). I will close this issue but feel free to let me know if you are running into any further issues :)
![info_badge_github_temp](https://user-images.githubusercontent.com/90726278/148120750-5f8b99f8-e4a7-43b2-87fa-838c4cdcf1ae.png)
