### ISSUE TITLE
SplitButton sample doesn't show full functionality

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/Xaml-Controls-Gallery#95]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [ ] New sample
- [ ] Addition to existing sample
- [x] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**
SplitButton

**Describe the sample**
[SplitButton Guidance](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/buttons#create-a-split-button) shows the event of clicking on the button to cycle to the next color.  The XAML Controls gallery sample with a similar example doesn't do this, so it's hard to see the behavior of the click action and how the control differs from the DropDownButton.

**Comment by YuliKl** [comment]
> SplitButton Guidance shows the event of clicking on the button to cycle to the next color. 

Maybe I'm missing something, but I don't think this is what the guidance sample is showing. To me, it looks like clicking the button changes the color of the selected text. The ChangeColor method is getting the Selection and changing its ForegroundColor. I don't see anything about cycling to the next color. @michael-hawker, am I looking in the wrong place?

**Comment by michael-hawker** [comment]
Sorry, it was late and I misread the sample from the docs. 😑

I didn't see the same context given to the one in the app to explain the sample though.

The first instinct as a dev is to play with the control, so I was trying to click on the button and expected some sort of change.  Maybe there should be some text in the box that's already highlighted?  Or use the bullet/bullet-type example where clicking the button will have a more immediately visible effect in the text without having to select something?

**Comment by chingucoding** [comment]
@YuliKL How should we proceed with this issue? Should we change the sample for the SplitButton?

**Comment by YuliKl** [comment]
@chingucoding, I'm not really sure how we fix this. What might be helpful is to pre-populate the TextBox with a Lorem Ipsum paragraph of text, making it easier for app users to highlight something without needing to type first. 

I'm not sure this fully addresses @michael-hawker's complaint, but it feels like a useful modification. I'd like to stick with colors as the sample swatches in the flyout rather than bullets or similar. And highlighted text is by its nature a temporary state, so the page shouldn't load with some of the text pre-highlighted.

**Comment by chingucoding** [comment]
I agree pre-populating the TextBox will make that easier. However if the user has to highlight the text before the changes from the SplitButton take effect, that still is a bit problematic.

Maybe we could change the behaviour, so that instead of coloring the highlighted text, it highlights the whole text. That way it is easier "to play around".

**Comment by YuliKl** [comment]
This sample is trying to show the behavior from Word's font color button 
![image](https://user-images.githubusercontent.com/13142665/63061041-c9be8400-bea8-11e9-96d2-c349b3191554.png)
In Word, already-typed, non-selected text doesn't get it's color updated.

**Comment by chingucoding** [comment]
Oh yes, that makes sense. I'll create a PR with the lorem ipsum added.
